In [1]:
#Numpy basic recap 




import numpy as np

In [2]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [3]:
x1

array([5, 0, 3, 3, 7, 9])

In [4]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [5]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [6]:
print("Dtype:",x3.dtype)

Dtype: int32


In [7]:
#arrary indexing 

x1

array([5, 0, 3, 3, 7, 9])

In [8]:
x1[0]

5

In [10]:
x1[-1]

9

In [11]:
x1[-2]

7

In [13]:
x2[0,0]

3

In [14]:
x2[0,2]

2

In [16]:
x2[2, -1]
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [17]:
x1[0] = 3.141
x1

array([3, 0, 3, 3, 7, 9])

In [19]:
#array slicing
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[:5]

array([0, 1, 2, 3, 4])

In [21]:
x[5:]

array([5, 6, 7, 8, 9])

In [22]:
x[::2]

array([0, 2, 4, 6, 8])

In [23]:
x[5::2]

array([5, 7, 9])

In [24]:
#Multidimensional wsubarray
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [25]:
x2[:2,::3]

array([[3, 4],
       [7, 8]])

In [26]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [27]:
print(x2[:, 0])

[3 7 1]


In [29]:
print(x2[0,:])

[3 5 2 4]


In [30]:
#Subarray as no -copy views

print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [33]:
x2_sub=x2[0,0]=99
print(x2_sub)

99


In [34]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [35]:
x2_subarray_copy = x2[:2,:2].copy()
print(x2_subarray_copy)

[[99  5]
 [ 7  6]]


In [36]:
x2_subarray_copy[0,0]=42
print(x2_subarray_copy)

[[42  5]
 [ 7  6]]


In [37]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [39]:
#Re-shaping the array


grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
r=np.array([1,2,3])
r.reshape((1,3))

array([[1, 2, 3]])

In [44]:
r.reshape((3,1))

array([[1],
       [2],
       [3]])

In [45]:
r[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [47]:
#Concatenation of array


x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
gird = np.array([1,2,3],
                 [4,5,6])

In [48]:
np.concatenate([gird, grid], axis=1)

NameError: name 'gird' is not defined